
spring:
  kafka:
    topics: "library-events"
    admin:
      properties:
        bootstrap-servers: localhost:9092,localhost:9093
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093
      group-id: library
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: com.example.libraryconsumer.config.CustomDeserializerAvro
      properties:
        specific:
          avro:
            reader: true
        schema.registry.url: http://localhost:8085
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092,localhost:9093
server:
  port: 8087
